- name: Git clone AUR helper
  git:
    repo: https://aur.archlinux.org/paru.git
    dest: /tmp/aur
  when: is_test is defined and not is_test

- name: Make AUR helper
  shell: makepkg -si --noconfirm --noprogressbar
  args:
    chdir: /tmp/aur
  when: is_test is defined and not is_test

- name: Clean up AUR helper
  file:
    path: /tmp/aur
    state: absent
  when: is_test is defined and not is_test
