# tasks file for ansible-role-packages
---
- name: Install common CLI packages
  become: true
  package:
    name: "{{ cli.common }}"
    state: present
  when: cli.common is defined and cli.enabled|default(false) == true

- name: Install Arch CLI packages
  become: true
  pacman:
    update_cache: true
    name: "{{ cli.arch}}"
    state: present
  when: ansible_os_family == "Archlinux" and cli.arch is defined and cli.enabled|default(false) == true

- name: Install Debian packages
  become: true
  apt:
    update_cache: true
    name: "{{ cli.debian }}"
    state: present
  when: ansible_os_family == "Debian" and cli.debian is defined and cli.enabled|default(false) == true

- name: Install common GUI packages
  become: true
  pacman:
    update_cache: true
    name: "{{ gui.common }}"
    state: present
  when: gui.common is defined and gui.enabled|default(false) == true

- name: Install Arch GUI packages
  become: true
  pacman:
    update_cache: true
    name: "{{ gui.arch }}"
    state: present
  when: ansible_os_family == "Archlinux" and gui.arch is defined and gui.enabled|default(false) == true

- name: Install Debian GUI packages
  become: true
  apt:
    update_cache: true
    name: "{{ gui.debian }}"
    state: present
  when: ansible_os_family == "Debian" and gui.debian is defined and gui.enabled|default(false) == true

- include_tasks: aur.yml
  when: ansible_os_family == "Archlinux" and install_aur_helper|default(false) == true
