# tasks file for ansible-role-packages
---
- name: Install common packages
  become: true
  package:
    name: "{{ common }}"
    state: present

- name: Install Arch packages
  become: true
  pacman:
    update_cache: true
    name: "{{ arch }}"
    state: present
  when: ansible_os_family == "Archlinux"

- name: Install Debian packages
  become: true
  apt:
    update_cache: true
    name: "{{ debian }}"
    state: present
  when: ansible_os_family == "Debian"

- include_tasks: aur.yml
  when: aur == true
