# tasks file for ansible-role-packages
---
- name: Update system
  become: true
  pacman:
    update_cache: true
    upgrade: true

- name: Install system packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages.sys }}"
    - "{{ packages.lang}}"
    - "{{ packages.cli }}"
    - "{{ packages.dev }}"
  tags: [packages]

- name: Install pip packages
  pip:
    name: "{{ packages.pip }}"
    state: present
  tags: [packages]

- name: Install yay
  include: yay.yml
  when: install_yay and run_in_molecule is defined and run_in_molecule == true
