# tasks file for ansible-role-packages
---
- name: Update system
  become: true
  pacman:
    update_cache: true
    upgrade: true

- name: Install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages.sys }}"
    - "{{ packages.lang}}"
    - "{{ packages.cli }}"
    - "{{ packages.dev }}"
  tags: [packages]
