---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: packages
    image: archlinux/base:latest
    dockerfile: Dockerfile.j2
    pull: false
    pre_build_image: false
provisioner:
  name: ansible
verifier:
  name: ansible
